-- GENERATED by scripts/load-event-e08.mjs — do not edit.
--
-- Event E08: the 20 April 2026 Wellington floods. 12 incidents compiled from
-- published journalism, each with its publication and article URL.
--
-- verification_level = 'media_reported', is_synthetic = false. These really
-- happened; they were not reported through this channel and must not be counted
-- as community reports.
--
-- Locations are coarsened per incident where the source describes a specific
-- dwelling and its occupants. See the header of the generator for the reasoning.

set search_path = public, extensions;

delete from silver.report where event_code = 'E08';

insert into silver.event (code, name, started_at, description, state_of_emergency) values
  ('E08', 'Wellington floods and slips, 20 April 2026',
   timestamptz '2026-04-20 00:00+12',
   'Record rainfall across Wellington overnight on 20 April 2026 caused widespread flooding and '
   || 'landslips. A state of emergency was declared. Incidents below are compiled from published '
   || 'news reporting, not from community reports.',
   true)
on conflict (code) do update
  set name = excluded.name, started_at = excluded.started_at,
      description = excluded.description, state_of_emergency = excluded.state_of_emergency;

-- Official advice, from NEMA / Civil Defence. Nothing here is written by us.
insert into silver.public_advice (fault_type, advice, source_url) values
  ('surface-flood', 'Do not walk, swim or drive through floodwater - just 15cm can sweep you off your feet, half a metre can carry away a car. If you see rising water, do not wait for official warnings: head for higher ground immediately. Floodwater is often contaminated. Only return home once Civil Defence/emergency services confirm it is safe.', 'https://www.civildefence.govt.nz/resources/what-to-do-during-a-flood-or-if-a-flood-is-imminent'),
  ('slip', 'If a landslide occurs, or the ground shows warning signs (new cracks, tilting trees/fences, doors/windows sticking, decks moving), evacuate immediately and call 111 if life is at risk. Stay away from the slip area until authorities give the all-clear - more slips can occur in the same place. Do not attempt to clear debris yourself. Report slips on public roads/land to the local council.', 'https://www.civildefence.govt.nz/emergency-events/advice-and-support/during-and-after-emergencies/during-a-landslide'),
  ('building-damage', 'If a building shows signs of structural failure, evacuate immediately and call 111. Do not re-enter a red- or yellow-placarded building. Stay clear until Council Building Control or engineers confirm it is safe.', 'https://www.civildefence.govt.nz/guidance-training/consistent-messages/landslide')
on conflict (fault_type, source_url) do update set advice = excluded.advice;

-- Incidents
insert into silver.report (
  reference, subject, service, fault_type, additional_fault_types, severity, fault_desc,
  geom, loc_address, loc_suburb, precision_override,
  reporter_kind, observed_at, submitted_at,
  verification_level, provenance, is_synthetic, source_channel,
  event_code, sub_event_code, source_url, source_publication, image_source_url,
  priority_override, description_public, pii_reviewed, raw_payload
) values (
  'WCC-E08-01', 'Incident compiled from published reporting', 'emergency',
  'slip', array['building-damage'], 'urgent', 'A house partially collapsed after a hillside slip undercut its foundations, leaving the structure dangling at the edge of an unstable slope. Street blocked by the slip.',
  extensions.st_setsrid(extensions.st_makepoint(174.7661, -41.3089), 4326),
  'Liardet Street', 'Vogeltown', 'zone_100m',
  'council', timestamptz '2026-04-20 03:45+12', timestamptz '2026-04-20 03:45+12',
  -- Corroborated, not confirmed: several outlets reported the event, and no
  -- Council record backs any individual incident. Provenance carries where it
  -- came from; the two are separate facts.
  'corroborated', 'media', false, 'media',
  'E08', 'E08-01', 'https://thespinoff.co.nz/society/20-04-2026/wellington-region-state-of-emergency-what-you-need-to-know', 'The Spinoff / NZ Herald (Mark Mitchell)', 'https://thespinoff.co.nz/society/20-04-2026/wellington-region-state-of-emergency-what-you-need-to-know',
  1, 'A house partially collapsed after a hillside slip undercut its foundations, leaving the structure dangling at the edge of an unstable slope. Street blocked by the slip.', true, '{"subEventId":"E08-01","parentEventId":"E08","eventTimeAsPublished":"03:45 (approx)","streetAsPublished":"Liardet Street","issueTypeAsPublished":"slip","priorityEstimate":1,"imageSourceUrl":"https://thespinoff.co.nz/society/20-04-2026/wellington-region-state-of-emergency-what-you-need-to-know"}'::jsonb
);
insert into silver.report_agency (report_id, agency_code, role)
select r.id, v.code, v.role from silver.report r,
  (values ('WCC-ROADS', 'lead'), ('WCC-BUILDING', 'assigned'), ('FENZ', 'life_safety')) as v(code, role)
where r.reference = 'WCC-E08-01';
insert into silver.report_status_event (report_id, status, note, actor_role, actor_label, at)
select r.id, 'reassessing', 'Status as published in reporting of the event.', 'wcc_duty_officer',
       'Compiled from published reporting', timestamptz '2026-04-20 03:45+12' + interval '6 hours'
from silver.report r where r.reference = 'WCC-E08-01';

insert into silver.report (
  reference, subject, service, fault_type, additional_fault_types, severity, fault_desc,
  geom, loc_address, loc_suburb, precision_override,
  reporter_kind, observed_at, submitted_at,
  verification_level, provenance, is_synthetic, source_channel,
  event_code, sub_event_code, source_url, source_publication, image_source_url,
  priority_override, description_public, pii_reviewed, raw_payload
) values (
  'WCC-E08-02', 'Incident compiled from published reporting', 'emergency',
  'slip', '{}'::text[], 'urgent', 'Landslip brought down large amounts of dirt, debris and material onto the street; residents assessed damage to properties along the street.',
  extensions.st_setsrid(extensions.st_makepoint(174.7735, -41.3175), 4326),
  'Balfour Street', 'Mornington', null,
  'council', timestamptz '2026-04-20 00:00+12', timestamptz '2026-04-20 00:00+12',
  -- Corroborated, not confirmed: several outlets reported the event, and no
  -- Council record backs any individual incident. Provenance carries where it
  -- came from; the two are separate facts.
  'corroborated', 'media', false, 'media',
  'E08', 'E08-02', 'https://www.rnz.co.nz/news/weather/592843/in-pictures-the-damage-caused-by-flooding-across-the-lower-north-island', 'RNZ (Samuel Rillstone)', 'https://www.rnz.co.nz/news/weather/592843/in-pictures-the-damage-caused-by-flooding-across-the-lower-north-island',
  1, 'Landslip brought down large amounts of dirt, debris and material onto the street; residents assessed damage to properties along the street.', true, '{"subEventId":"E08-02","parentEventId":"E08","eventTimeAsPublished":"00:00 (approx)","streetAsPublished":"Balfour Street","issueTypeAsPublished":"slip","priorityEstimate":1,"imageSourceUrl":"https://www.rnz.co.nz/news/weather/592843/in-pictures-the-damage-caused-by-flooding-across-the-lower-north-island"}'::jsonb
);
insert into silver.report_agency (report_id, agency_code, role)
select r.id, v.code, v.role from silver.report r,
  (values ('WCC-ROADS', 'lead')) as v(code, role)
where r.reference = 'WCC-E08-02';
insert into silver.report_status_event (report_id, status, note, actor_role, actor_label, at)
select r.id, 'completed_confirmed', 'Status as published in reporting of the event.', 'wcc_duty_officer',
       'Compiled from published reporting', timestamptz '2026-04-20 00:00+12' + interval '6 hours'
from silver.report r where r.reference = 'WCC-E08-02';

insert into silver.report (
  reference, subject, service, fault_type, additional_fault_types, severity, fault_desc,
  geom, loc_address, loc_suburb, precision_override,
  reporter_kind, observed_at, submitted_at,
  verification_level, provenance, is_synthetic, source_channel,
  event_code, sub_event_code, source_url, source_publication, image_source_url,
  priority_override, description_public, pii_reviewed, raw_payload
) values (
  'WCC-E08-03', 'Incident compiled from published reporting', 'emergency',
  'surface-flood', '{}'::text[], 'urgent', 'Significant surface flooding recorded along Adelaide Road; adjacent section of SH1 between Ellice Street and Adelaide Road reduced to one lane for much of the day.',
  extensions.st_setsrid(extensions.st_makepoint(174.7745, -41.3195), 4326),
  'Adelaide Road', 'Berhampore', null,
  'council', timestamptz '2026-04-20 03:45+12', timestamptz '2026-04-20 03:45+12',
  -- Corroborated, not confirmed: several outlets reported the event, and no
  -- Council record backs any individual incident. Provenance carries where it
  -- came from; the two are separate facts.
  'corroborated', 'media', false, 'media',
  'E08', 'E08-03', 'https://wellington.scoop.co.nz/?p=179320', 'Wellington.Scoop / RNZ / Police', 'https://wellington.scoop.co.nz/?p=179320',
  1, 'Significant surface flooding recorded along Adelaide Road; adjacent section of SH1 between Ellice Street and Adelaide Road reduced to one lane for much of the day.', true, '{"subEventId":"E08-03","parentEventId":"E08","eventTimeAsPublished":"03:45","streetAsPublished":"Adelaide Road","issueTypeAsPublished":"surface-flood","priorityEstimate":1,"imageSourceUrl":"https://wellington.scoop.co.nz/?p=179320"}'::jsonb
);
insert into silver.report_agency (report_id, agency_code, role)
select r.id, v.code, v.role from silver.report r,
  (values ('WELLINGTON-WATER', 'assigned')) as v(code, role)
where r.reference = 'WCC-E08-03';
insert into silver.report_status_event (report_id, status, note, actor_role, actor_label, at)
select r.id, 'completed_confirmed', 'Status as published in reporting of the event.', 'wcc_duty_officer',
       'Compiled from published reporting', timestamptz '2026-04-20 03:45+12' + interval '6 hours'
from silver.report r where r.reference = 'WCC-E08-03';

insert into silver.report (
  reference, subject, service, fault_type, additional_fault_types, severity, fault_desc,
  geom, loc_address, loc_suburb, precision_override,
  reporter_kind, observed_at, submitted_at,
  verification_level, provenance, is_synthetic, source_channel,
  event_code, sub_event_code, source_url, source_publication, image_source_url,
  priority_override, description_public, pii_reviewed, raw_payload
) values (
  'WCC-E08-04', 'Incident compiled from published reporting', 'emergency',
  'surface-flood', '{}'::text[], 'disruption', 'A car was lifted by floodwater and dumped onto a fence.',
  extensions.st_setsrid(extensions.st_makepoint(174.7755, -41.321), 4326),
  'Emerson Street', 'Berhampore', null,
  'council', timestamptz '2026-04-20 00:00+12', timestamptz '2026-04-20 00:00+12',
  -- Corroborated, not confirmed: several outlets reported the event, and no
  -- Council record backs any individual incident. Provenance carries where it
  -- came from; the two are separate facts.
  'corroborated', 'media', false, 'media',
  'E08', 'E08-04', 'https://www.1news.co.nz/2026/04/20/in-images-wellington-slammed-by-heavy-rain-flooding-landslips/', '1News', 'https://www.1news.co.nz/2026/04/20/in-images-wellington-slammed-by-heavy-rain-flooding-landslips/',
  2, 'A car was lifted by floodwater and dumped onto a fence.', true, '{"subEventId":"E08-04","parentEventId":"E08","eventTimeAsPublished":"00:00 (approx)","streetAsPublished":"Emerson Street","issueTypeAsPublished":"surface-flood","priorityEstimate":2,"imageSourceUrl":"https://www.1news.co.nz/2026/04/20/in-images-wellington-slammed-by-heavy-rain-flooding-landslips/"}'::jsonb
);
insert into silver.report_agency (report_id, agency_code, role)
select r.id, v.code, v.role from silver.report r,
  (values ('WELLINGTON-WATER', 'assigned')) as v(code, role)
where r.reference = 'WCC-E08-04';
insert into silver.report_status_event (report_id, status, note, actor_role, actor_label, at)
select r.id, 'completed_confirmed', 'Status as published in reporting of the event.', 'wcc_duty_officer',
       'Compiled from published reporting', timestamptz '2026-04-20 00:00+12' + interval '6 hours'
from silver.report r where r.reference = 'WCC-E08-04';

insert into silver.report (
  reference, subject, service, fault_type, additional_fault_types, severity, fault_desc,
  geom, loc_address, loc_suburb, precision_override,
  reporter_kind, observed_at, submitted_at,
  verification_level, provenance, is_synthetic, source_channel,
  event_code, sub_event_code, source_url, source_publication, image_source_url,
  priority_override, description_public, pii_reviewed, raw_payload
) values (
  'WCC-E08-05', 'Incident compiled from published reporting', 'emergency',
  'surface-flood', '{}'::text[], 'urgent', 'Flash flooding around 3:45am pushed cars down driveways and under garages; firefighters axed elderly residents out of their homes and carried them through floodwaters to safety.',
  extensions.st_setsrid(extensions.st_makepoint(174.775, -41.32), 4326),
  'Akatea Street', 'Berhampore', 'zone_100m',
  'council', timestamptz '2026-04-20 03:45+12', timestamptz '2026-04-20 03:45+12',
  -- Corroborated, not confirmed: several outlets reported the event, and no
  -- Council record backs any individual incident. Provenance carries where it
  -- came from; the two are separate facts.
  'corroborated', 'media', false, 'media',
  'E08', 'E08-05', 'https://www.odt.co.nz/news/national/nightmare-slips-and-widespread-flooding-hit-wellington-rnz', 'ODT / RNZ (Ellen O''Dwyer)', 'https://www.odt.co.nz/news/national/nightmare-slips-and-widespread-flooding-hit-wellington-rnz',
  1, 'Flash flooding around 3:45am pushed cars down driveways and under garages; firefighters axed elderly residents out of their homes and carried them through floodwaters to safety.', true, '{"subEventId":"E08-05","parentEventId":"E08","eventTimeAsPublished":"03:45","streetAsPublished":"Akatea Street","issueTypeAsPublished":"surface-flood","priorityEstimate":1,"imageSourceUrl":"https://www.odt.co.nz/news/national/nightmare-slips-and-widespread-flooding-hit-wellington-rnz"}'::jsonb
);
insert into silver.report_agency (report_id, agency_code, role)
select r.id, v.code, v.role from silver.report r,
  (values ('WELLINGTON-WATER', 'assigned'), ('FENZ', 'life_safety')) as v(code, role)
where r.reference = 'WCC-E08-05';
insert into silver.report_status_event (report_id, status, note, actor_role, actor_label, at)
select r.id, 'completed_confirmed', 'Status as published in reporting of the event.', 'wcc_duty_officer',
       'Compiled from published reporting', timestamptz '2026-04-20 03:45+12' + interval '6 hours'
from silver.report r where r.reference = 'WCC-E08-05';

insert into silver.report (
  reference, subject, service, fault_type, additional_fault_types, severity, fault_desc,
  geom, loc_address, loc_suburb, precision_override,
  reporter_kind, observed_at, submitted_at,
  verification_level, provenance, is_synthetic, source_channel,
  event_code, sub_event_code, source_url, source_publication, image_source_url,
  priority_override, description_public, pii_reviewed, raw_payload
) values (
  'WCC-E08-06', 'Incident compiled from published reporting', 'emergency',
  'slip', '{}'::text[], 'urgent', 'A major landslide brought down large amounts of dirt, rocks and trees, blocking a residential street and cutting off access to several properties.',
  extensions.st_setsrid(extensions.st_makepoint(174.7695, -41.3245), 4326),
  null, 'Kingston', 'zone_100m',
  'council', timestamptz '2026-04-20 00:00+12', timestamptz '2026-04-20 00:00+12',
  -- Corroborated, not confirmed: several outlets reported the event, and no
  -- Council record backs any individual incident. Provenance carries where it
  -- came from; the two are separate facts.
  'corroborated', 'media', false, 'media',
  'E08', 'E08-06', 'https://www.rnz.co.nz/news/weather/592843/in-pictures-the-damage-caused-by-flooding-across-the-lower-north-island', 'RNZ (Mark Papalii)', 'https://www.rnz.co.nz/news/weather/592843/in-pictures-the-damage-caused-by-flooding-across-the-lower-north-island',
  1, 'A major landslide brought down large amounts of dirt, rocks and trees, blocking a residential street and cutting off access to several properties.', true, '{"subEventId":"E08-06","parentEventId":"E08","eventTimeAsPublished":"00:00 (approx)","streetAsPublished":null,"issueTypeAsPublished":"slip","priorityEstimate":1,"imageSourceUrl":"https://www.rnz.co.nz/news/weather/592843/in-pictures-the-damage-caused-by-flooding-across-the-lower-north-island"}'::jsonb
);
insert into silver.report_agency (report_id, agency_code, role)
select r.id, v.code, v.role from silver.report r,
  (values ('WCC-ROADS', 'lead')) as v(code, role)
where r.reference = 'WCC-E08-06';
insert into silver.report_status_event (report_id, status, note, actor_role, actor_label, at)
select r.id, 'fixed', 'Status as published in reporting of the event.', 'wcc_duty_officer',
       'Compiled from published reporting', timestamptz '2026-04-20 00:00+12' + interval '6 hours'
from silver.report r where r.reference = 'WCC-E08-06';

insert into silver.report (
  reference, subject, service, fault_type, additional_fault_types, severity, fault_desc,
  geom, loc_address, loc_suburb, precision_override,
  reporter_kind, observed_at, submitted_at,
  verification_level, provenance, is_synthetic, source_channel,
  event_code, sub_event_code, source_url, source_publication, image_source_url,
  priority_override, description_public, pii_reviewed, raw_payload
) values (
  'WCC-E08-07', 'Incident compiled from published reporting', 'emergency',
  'surface-flood', '{}'::text[], 'urgent', 'The suburb''s main street was completely submerged; firefighters pumped knee-high water out of multiple houses.',
  extensions.st_setsrid(extensions.st_makepoint(174.7754, -41.3355), 4326),
  'The Parade', 'Island Bay', null,
  'council', timestamptz '2026-04-20 00:00+12', timestamptz '2026-04-20 00:00+12',
  -- Corroborated, not confirmed: several outlets reported the event, and no
  -- Council record backs any individual incident. Provenance carries where it
  -- came from; the two are separate facts.
  'corroborated', 'media', false, 'media',
  'E08', 'E08-07', 'https://www.thepost.co.nz/nz-news/360988981/flooding-across-wellington-after-night-severe-rain-avoid-non-essential-travel', 'The Post', 'https://www.thepost.co.nz/nz-news/360988981/flooding-across-wellington-after-night-severe-rain-avoid-non-essential-travel',
  1, 'The suburb''s main street was completely submerged; firefighters pumped knee-high water out of multiple houses.', true, '{"subEventId":"E08-07","parentEventId":"E08","eventTimeAsPublished":"00:00 (approx)","streetAsPublished":"The Parade","issueTypeAsPublished":"surface-flood","priorityEstimate":1,"imageSourceUrl":"https://www.thepost.co.nz/nz-news/360988981/flooding-across-wellington-after-night-severe-rain-avoid-non-essential-travel"}'::jsonb
);
insert into silver.report_agency (report_id, agency_code, role)
select r.id, v.code, v.role from silver.report r,
  (values ('WELLINGTON-WATER', 'assigned'), ('FENZ', 'life_safety')) as v(code, role)
where r.reference = 'WCC-E08-07';
insert into silver.report_status_event (report_id, status, note, actor_role, actor_label, at)
select r.id, 'completed_confirmed', 'Status as published in reporting of the event.', 'wcc_duty_officer',
       'Compiled from published reporting', timestamptz '2026-04-20 00:00+12' + interval '6 hours'
from silver.report r where r.reference = 'WCC-E08-07';

insert into silver.report (
  reference, subject, service, fault_type, additional_fault_types, severity, fault_desc,
  geom, loc_address, loc_suburb, precision_override,
  reporter_kind, observed_at, submitted_at,
  verification_level, provenance, is_synthetic, source_channel,
  event_code, sub_event_code, source_url, source_publication, image_source_url,
  priority_override, description_public, pii_reviewed, raw_payload
) values (
  'WCC-E08-08', 'Incident compiled from published reporting', 'emergency',
  'surface-flood', '{}'::text[], 'urgent', 'At least one vehicle was swept roughly 150 metres along the road and into the tide.',
  extensions.st_setsrid(extensions.st_makepoint(174.762, -41.3395), 4326),
  'Happy Valley Road', 'Owhiro Bay', null,
  'council', timestamptz '2026-04-20 00:00+12', timestamptz '2026-04-20 00:00+12',
  -- Corroborated, not confirmed: several outlets reported the event, and no
  -- Council record backs any individual incident. Provenance carries where it
  -- came from; the two are separate facts.
  'corroborated', 'media', false, 'media',
  'E08', 'E08-08', 'https://newswire.co.nz/2026/04/wellington-declares-state-of-emergency-as-record-flooding-sweeps-through-the-capital/', 'NEWS WIRE', 'https://newswire.co.nz/2026/04/wellington-declares-state-of-emergency-as-record-flooding-sweeps-through-the-capital/',
  1, 'At least one vehicle was swept roughly 150 metres along the road and into the tide.', true, '{"subEventId":"E08-08","parentEventId":"E08","eventTimeAsPublished":"00:00 (approx)","streetAsPublished":"Happy Valley Road","issueTypeAsPublished":"surface-flood","priorityEstimate":1,"imageSourceUrl":"https://newswire.co.nz/2026/04/wellington-declares-state-of-emergency-as-record-flooding-sweeps-through-the-capital/"}'::jsonb
);
insert into silver.report_agency (report_id, agency_code, role)
select r.id, v.code, v.role from silver.report r,
  (values ('WELLINGTON-WATER', 'assigned')) as v(code, role)
where r.reference = 'WCC-E08-08';
insert into silver.report_status_event (report_id, status, note, actor_role, actor_label, at)
select r.id, 'completed_confirmed', 'Status as published in reporting of the event.', 'wcc_duty_officer',
       'Compiled from published reporting', timestamptz '2026-04-20 00:00+12' + interval '6 hours'
from silver.report r where r.reference = 'WCC-E08-08';

insert into silver.report (
  reference, subject, service, fault_type, additional_fault_types, severity, fault_desc,
  geom, loc_address, loc_suburb, precision_override,
  reporter_kind, observed_at, submitted_at,
  verification_level, provenance, is_synthetic, source_channel,
  event_code, sub_event_code, source_url, source_publication, image_source_url,
  priority_override, description_public, pii_reviewed, raw_payload
) values (
  'WCC-E08-09', 'Incident compiled from published reporting', 'emergency',
  'slip', array['building-damage'], 'urgent', 'A resident woke to a landslide collapsing part of a bedroom wall.',
  extensions.st_setsrid(extensions.st_makepoint(174.7666, -41.3059), 4326),
  null, 'Brooklyn', 'zone_100m',
  'council', timestamptz '2026-04-20 00:00+12', timestamptz '2026-04-20 00:00+12',
  -- Corroborated, not confirmed: several outlets reported the event, and no
  -- Council record backs any individual incident. Provenance carries where it
  -- came from; the two are separate facts.
  'corroborated', 'media', false, 'media',
  'E08', 'E08-09', 'https://www.insurancebusinessmag.com/nz/news/catastrophe/state-of-emergency-in-wellington-record-rain-overwhelms-capital-as-insurers-brace-for-claims-surge-572251.aspx', 'Insurance Business', 'https://www.insurancebusinessmag.com/nz/news/catastrophe/state-of-emergency-in-wellington-record-rain-overwhelms-capital-as-insurers-brace-for-claims-surge-572251.aspx',
  1, 'A resident woke to a landslide collapsing part of a bedroom wall.', true, '{"subEventId":"E08-09","parentEventId":"E08","eventTimeAsPublished":"00:00 (approx)","streetAsPublished":null,"issueTypeAsPublished":"slip","priorityEstimate":1,"imageSourceUrl":"https://www.insurancebusinessmag.com/nz/news/catastrophe/state-of-emergency-in-wellington-record-rain-overwhelms-capital-as-insurers-brace-for-claims-surge-572251.aspx"}'::jsonb
);
insert into silver.report_agency (report_id, agency_code, role)
select r.id, v.code, v.role from silver.report r,
  (values ('WCC-ROADS', 'lead'), ('WCC-BUILDING', 'assigned')) as v(code, role)
where r.reference = 'WCC-E08-09';
insert into silver.report_status_event (report_id, status, note, actor_role, actor_label, at)
select r.id, 'reassessing', 'Status as published in reporting of the event.', 'wcc_duty_officer',
       'Compiled from published reporting', timestamptz '2026-04-20 00:00+12' + interval '6 hours'
from silver.report r where r.reference = 'WCC-E08-09';

insert into silver.report (
  reference, subject, service, fault_type, additional_fault_types, severity, fault_desc,
  geom, loc_address, loc_suburb, precision_override,
  reporter_kind, observed_at, submitted_at,
  verification_level, provenance, is_synthetic, source_channel,
  event_code, sub_event_code, source_url, source_publication, image_source_url,
  priority_override, description_public, pii_reviewed, raw_payload
) values (
  'WCC-E08-10', 'Incident compiled from published reporting', 'emergency',
  'slip', '{}'::text[], 'disruption', 'Landslide reported in Miramar; slips blocked roads and damaged property in the area.',
  extensions.st_setsrid(extensions.st_makepoint(174.8172, -41.3179), 4326),
  null, 'Miramar', null,
  'council', timestamptz '2026-04-20 00:00+12', timestamptz '2026-04-20 00:00+12',
  -- Corroborated, not confirmed: several outlets reported the event, and no
  -- Council record backs any individual incident. Provenance carries where it
  -- came from; the two are separate facts.
  'corroborated', 'media', false, 'media',
  'E08', 'E08-10', 'https://watchers.news/2026/04/21/record-rainfall-triggers-flooding-evacuations-wellington-new-zealand-one-person-missing-april-2026/', 'The Watchers', 'https://watchers.news/2026/04/21/record-rainfall-triggers-flooding-evacuations-wellington-new-zealand-one-person-missing-april-2026/',
  2, 'Landslide reported in Miramar; slips blocked roads and damaged property in the area.', true, '{"subEventId":"E08-10","parentEventId":"E08","eventTimeAsPublished":"00:00 (approx)","streetAsPublished":null,"issueTypeAsPublished":"slip","priorityEstimate":2,"imageSourceUrl":"https://watchers.news/2026/04/21/record-rainfall-triggers-flooding-evacuations-wellington-new-zealand-one-person-missing-april-2026/"}'::jsonb
);
insert into silver.report_agency (report_id, agency_code, role)
select r.id, v.code, v.role from silver.report r,
  (values ('WCC-ROADS', 'lead')) as v(code, role)
where r.reference = 'WCC-E08-10';
insert into silver.report_status_event (report_id, status, note, actor_role, actor_label, at)
select r.id, 'fixed', 'Status as published in reporting of the event.', 'wcc_duty_officer',
       'Compiled from published reporting', timestamptz '2026-04-20 00:00+12' + interval '6 hours'
from silver.report r where r.reference = 'WCC-E08-10';

insert into silver.report (
  reference, subject, service, fault_type, additional_fault_types, severity, fault_desc,
  geom, loc_address, loc_suburb, precision_override,
  reporter_kind, observed_at, submitted_at,
  verification_level, provenance, is_synthetic, source_channel,
  event_code, sub_event_code, source_url, source_publication, image_source_url,
  priority_override, description_public, pii_reviewed, raw_payload
) values (
  'WCC-E08-11', 'Incident compiled from published reporting', 'emergency',
  'surface-flood', '{}'::text[], 'urgent', 'A property was struck by floodwaters and debris. A search and rescue operation for a resident reported missing from the address continued over subsequent days along the Karori Stream and nearby waterways.',
  extensions.st_setsrid(extensions.st_makepoint(174.7255, -41.2765), 4326),
  'Karori South Road', 'South Karori', 'suburb',
  'council', timestamptz '2026-04-20 00:00+12', timestamptz '2026-04-20 00:00+12',
  -- Corroborated, not confirmed: several outlets reported the event, and no
  -- Council record backs any individual incident. Provenance carries where it
  -- came from; the two are separate facts.
  'corroborated', 'media', false, 'media',
  'E08', 'E08-11', 'https://www.thepost.co.nz/nz-news/360988981/flooding-across-wellington-after-night-severe-rain-avoid-non-essential-travel', 'The Post / NZ Police', 'https://www.thepost.co.nz/nz-news/360988981/flooding-across-wellington-after-night-severe-rain-avoid-non-essential-travel',
  1, 'A property was struck by floodwaters and debris. A search and rescue operation for a resident reported missing from the address continued over subsequent days along the Karori Stream and nearby waterways.', true, '{"subEventId":"E08-11","parentEventId":"E08","eventTimeAsPublished":"00:00 (approx)","streetAsPublished":"Karori South Road","issueTypeAsPublished":"surface-flood","priorityEstimate":1,"imageSourceUrl":"https://www.thepost.co.nz/nz-news/360988981/flooding-across-wellington-after-night-severe-rain-avoid-non-essential-travel"}'::jsonb
);
insert into silver.report_agency (report_id, agency_code, role)
select r.id, v.code, v.role from silver.report r,
  (values ('WELLINGTON-WATER', 'assigned'), ('FENZ', 'life_safety')) as v(code, role)
where r.reference = 'WCC-E08-11';
insert into silver.report_status_event (report_id, status, note, actor_role, actor_label, at)
select r.id, 'under_review', 'Status as published in reporting of the event.', 'wcc_duty_officer',
       'Compiled from published reporting', timestamptz '2026-04-20 00:00+12' + interval '6 hours'
from silver.report r where r.reference = 'WCC-E08-11';

insert into silver.report (
  reference, subject, service, fault_type, additional_fault_types, severity, fault_desc,
  geom, loc_address, loc_suburb, precision_override,
  reporter_kind, observed_at, submitted_at,
  verification_level, provenance, is_synthetic, source_channel,
  event_code, sub_event_code, source_url, source_publication, image_source_url,
  priority_override, description_public, pii_reviewed, raw_payload
) values (
  'WCC-E08-12', 'Incident compiled from published reporting', 'emergency',
  'surface-flood', '{}'::text[], 'disruption', 'A flash flood around 4am hit the hospital''s underground car park, affecting the area where Wellington Free Ambulance vehicles were located; firefighters pumped out the car park.',
  extensions.st_setsrid(extensions.st_makepoint(174.7787, -41.3128), 4326),
  'Wellington Regional Hospital precinct', 'Newtown', null,
  'council', timestamptz '2026-04-20 04:00+12', timestamptz '2026-04-20 04:00+12',
  -- Corroborated, not confirmed: several outlets reported the event, and no
  -- Council record backs any individual incident. Provenance carries where it
  -- came from; the two are separate facts.
  'corroborated', 'media', false, 'media',
  'E08', 'E08-12', 'https://www.1news.co.nz/2026/04/20/in-images-wellington-slammed-by-heavy-rain-flooding-landslips/', '1News', 'https://www.1news.co.nz/2026/04/20/in-images-wellington-slammed-by-heavy-rain-flooding-landslips/',
  2, 'A flash flood around 4am hit the hospital''s underground car park, affecting the area where Wellington Free Ambulance vehicles were located; firefighters pumped out the car park.', true, '{"subEventId":"E08-12","parentEventId":"E08","eventTimeAsPublished":"04:00 (approx)","streetAsPublished":"Wellington Regional Hospital precinct","issueTypeAsPublished":"surface-flood","priorityEstimate":2,"imageSourceUrl":"https://www.1news.co.nz/2026/04/20/in-images-wellington-slammed-by-heavy-rain-flooding-landslips/"}'::jsonb
);
insert into silver.report_agency (report_id, agency_code, role)
select r.id, v.code, v.role from silver.report r,
  (values ('WELLINGTON-WATER', 'assigned'), ('FENZ', 'life_safety')) as v(code, role)
where r.reference = 'WCC-E08-12';
insert into silver.report_status_event (report_id, status, note, actor_role, actor_label, at)
select r.id, 'completed_confirmed', 'Status as published in reporting of the event.', 'wcc_duty_officer',
       'Compiled from published reporting', timestamptz '2026-04-20 04:00+12' + interval '6 hours'
from silver.report r where r.reference = 'WCC-E08-12';

select silver.rebuild_clusters();